name: PR Validation
on:  
  pull_request:
    branches:
      - develop
      - main

jobs:  
  lint:
    name: Lint
    runs-on: cipherauth-gha-runner-scale-set
    steps:
      # Add Code as required
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Checkout repo
      #   uses: actions/checkout@v4
      # - name: Install Yarn
      #   run: |
      #     npm install --global yarn
      # - name: Yarn Version
      #   run: |
      #     yarn --version
      # - name: Yarn Install
      #   run: |
      #     yarn install
      # - name: Run Lint
      #   run: |
      #     yarn lint